### PR TITLE
Script to convert CVRPTW benchmark files to VROOM

### PR DESCRIPTION
**Pull request by sashakh**
Adding .gitignore file to hide generated *.pyc files from status
 
## Tasks

 - [ ] review
 - [ ] merge

### CODE REVIEW

**Comment by sashakh** [comment]
## Issue #1 

CVRPTW benchmark to VROOM input json files conversion script.

Use the same concept as ```cvrplib_to_json.py```, the differences in this script are:
- it doesn't replace file extension, but just appends with '.json'
- it writes output file in current directory

## Tasks

 - [ ] update docs
 - [ ] review
 - [ ] merge

**Comment by sashakh** [comment]
Sorry about mess with this PR. Unfortunately GitHub doesn't know to make two separate PRs on the same branch.

**Comment by jcoupey** [comment]
Thanks for this PR!

I ran a quick test with both a TSPTW instance from your previous link and an instance from Solomon. Formats seem to be somehow compatible, can you confirm that?

Another question since you took a dive into the TSPTW benchmarks: is there a consensus to use the same integer rounding rule as for TSPLIB?
Unfortunately, for Solomon and Homberger instances, solutions reported in papers use double precision, which make comparisons harder, especially as there is no strict rounding rule.

**Comment by sashakh** [comment]
Hi Julien!
> Formats seem to be somehow compatible, can you confirm that?

Yes, formats are close. I've tries to handle both variants in the script (tested with selected files only).
> is there a consensus to use the same integer rounding rule as for TSPLIB?

The answer is yes, we can do what we wish. Do you mean ```int(x + 0.5)```? If yes I can add this.

Sasha

**Comment by jcoupey** [comment]
> Do you mean `int(x + 0.5)`?

Yes, if the TSPTW instances follow that convention for euclidean distance rounding, then it's fine as the `get_matrix` function you re-used already takes care of the rounding.

My point is that we need to follow those conventions in order to have a meaningful comparison between our solutions and the best known solutions published.

And sadly, it's different for Solomon/Homberger benchmarks where no rounding is expected. On the other hand, using floating point is calling for trouble (and would require to adjust the solver cost type and input parsing). Maybe we could round the euclidean distance to `x` decimal places, then multiply all costs by `10^x` to deal with integers. Then we'd only have to do the same for best known solutions costs to have a fair comparison.

**Comment by sashakh** [comment]
Tested converter against all benchmarks. Specifically:
- [Solomon 100](https://www.sintef.no/globalassets/project/top/vrptw/solomon/solomon-100.zip)
- [Homeberger 200](https://www.sintef.no/globalassets/project/top/vrptw/homberger/200/homberger_200_customer_instances.zip)
- [Homeberger 400](https://www.sintef.no/globalassets/project/top/vrptw/homberger/400/homberger_400_customer_instances.zip)
- [Homeberger 600](https://www.sintef.no/globalassets/project/top/vrptw/homberger/600/homberger_600_customer_instances.zip)
- [Homeberger 800](https://www.sintef.no/globalassets/project/top/vrptw/homberger/800/homberger_800_customer_instances.zip)
- [Homberger 1000](https://www.sintef.no/globalassets/project/top/vrptw/homberger/1000/homberger_1000_customer_instances.zip)
- [Everything from da Silva, R. F., Urrutia, S.](http://homepages.dcc.ufmg.br/~rfsilva/tsptw/ins/)

Works as expected. VROOM works over generated file as well (using '-l' libosrm flag, didn't check wirg routed). )

**Comment by sashakh** [comment]
I've looked over benchmarks. In all files actually integer values are used (in some they are defined as XY.00, but there are no numbers other than .00 ended). So with input we should be fine.

Regarding results. I don't know really how them were calculated. In [TSPTW](https://github.com/sashakh/TSPTW) distance matrix is calculated in ```tsptwreader.cpp``` as :
```C++
            double px = pow(tspPoint1->x - tspPoint2->x, 2);
            double py = pow(tspPoint1->y - tspPoint2->y, 2);
            int dist = (int)floor(sqrt(px + py));
            tsp->setDistance(i, j, dist + (int)tspPoint1->service);
            tsp->setDistance(j, i, dist + (int)tspPoint2->service);
```
We can change to +0.5 rounding there.

Am I missing something else?

**Comment by jcoupey** [comment]
> using '-l' libosrm flag

There will actually be no call to OSRM as the matrix is produced by the python script and directly parsed from the json files. My concern was to make sure to get the same matrix as the one used in the original articles. Unfortunately it's very hard to really know how costs where computed. There is a rough explanation [here](http://myweb.uiowa.edu/bthoa/TSPTWBenchmarkDataSets.htm)...

The best thing to do is probably to reuse the `int dist = (int)floor(sqrt(px + py));` rounding from the code snippet you posted for all TSPTW instances. Then we'll see how to handle other cases if required.

What do you think of adding a parameter to the `get_matrix` function to pass the expected rounding behaviour and then adjusting the computation in `src/utils/benchmark.py` accordingly?

**Pull request merged**
