### PR TITLE
CVRP TW benchmarks

### PR DESCRIPTION
**Pull request by sashakh**
This PR tries to address #1 by adding CVRP TW benchmarks sets downloader and processor, which I hope will be helpful in [VROOM-Project#113](https://github.com/VROOM-Project/vroom/issues/113) development. Currently there are two sets of sets:
- [VRPTW](https://www.sintef.no/projectweb/top/vrptw)
- [TSPTW](http://homepages.dcc.ufmg.br/~rfsilva/tsptw)

To download: `./download.sh` (only once)
To build BKS: `./build_BKS.py` (only once, or `./run.sh` will run it by itself)
To solve and compare: `./run.sh`

### CODE REVIEW

**Comment by jcoupey** [comment]
Thanks for this work! Nice to be able to run the same script on various benchmark sources.

I like the idea of a self-contained repo where all instances are available without any dependency to third-party websites. What do you think about commiting the instances themselves in relevant folders (TSPTW, VRPTW etc.) and still keeping your download script to automate update checks?
The same could also be applied for the best known solution compilation file.

**Comment by sashakh** [comment]
Sure, don't see any problem with it, and yes, we can still use ```download.sh``` and ```build_BKS.py``` scripts for updates.
I've committed the 3rd party instances, solutions and BKS.json files. Also renamed CVRPTW to VRPTW as you suggested.

**Comment by jcoupey** [comment]
On branching: I don't think it makes sense to merge #2 any time before this PR. What do you think if we keep your `cvrptw-benchmarks` branch as the reference during the TW feature development in the `vroom` repo, and then merge it once the feature is functional? (In that case I guess we could close #2 and keep all benchmarks-related discussions here?)

**Comment by jcoupey** [comment]
I've taken over to make a few adjustments before merging this branch.

@sashakh thanks again for your work on all the scripts to parse instances and compile best known solutions from various sources!

**Comment by jcoupey** [comment]
I've taken over to make a few adjustments before merging this branch.

@sashakh thanks again for your work on all the scripts to parse instances and compile best known solutions from various sources!

**Pull request merged**
