### PR TITLE
Add pre-commit-hooks to pre-commit config

### PR DESCRIPTION
**Pull request by sadikkuzu**
Add pre-commit-hooks to pre-commit config.

* Add `id: check-yaml` for checking `.pre-commit-config.yaml`

### CODE REVIEW

**Comment by jcoupey** [comment]
Thanks for the suggestion. If I get it right, since we don't have any other yaml file in the repo this comes down to a syntax check for `.pre-commit-config.yaml`?

**Comment by sadikkuzu** [comment]
My pleasure 🙏

Yes, you're right. It'll act on changes of only .pre-commit-config.yaml.

Moreover, this can be added for `setup.cfg`:

```diff
repos:
  - repo: https://github.com/psf/black
    rev: 21.5b2
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
+  - repo: https://github.com/asottile/setup-cfg-fmt
+    rev: v1.17.0
+    hooks:
+      - id: setup-cfg-fmt
```

**Comment by jcoupey** [comment]
My point is that I don't expect the `.pre-commit-config.yaml` or `setup.cfg` files to change any time soon (or not often anyway), so maybe pulling some third party code and adding checks on each new commit is a bit overkill.

**Comment by jcoupey** [comment]
Closing as this looks a bit overkill for our need and toolchain. Thanks anyway @sadikkuzu for the suggestion!

**Pull request closed without merging**
